### ISSUE TITLE
Forsiden på previsto.com lyver

### ISSUE THREAD

**Issue by michaelkrog** [xenabiz/previsto-site#3]
Vores forside på previsto.com siger følgende:
> Vores web-brugerflade er tiltænkt alle moderne enheder. Brugerfladen er derfor som skabt til din enhed hvad enten det er en computer, tablet eller smartphone. Med andre ord: Du kan have det fulde overblik med dig uanset hvor du befinder dig.

Det er en lodret løgn! :)  Vi har netop spærret for brug af den på små skærme. Hvad gør vi?

@Christianasanti @webspas

**Comment by Christianasanti** [comment]
Ordlyden er ændret.
Skal ændres når vi har app klar.

**Comment by webspas** [comment]
hehe... det kommer ved an på om vi tæller appen med?

**Comment by Christianasanti** [comment]
Planen er vist at når man tilgår siden vil man blive bedt om at  hente app´en eller åbne i app :)
